# -*- coding: utf-8 -*-
"""Winrate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xy5zCpmCccmhDEsOWeDU5VK5lVbLuajl
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pylab as pl
# %matplotlib inline

#Read the dataset
df = pd.read_csv('/content/GenteLol.csv')

#correlations between data
df.corr()

# correlation graphs
import seaborn as sns

sns.pairplot(df)

#get the fields of interest
$dataX= df[[ 'GP', 'KDA', 'GD10', 'XPD10', 'CSD10']]
dataY = df[['W%']]
dataX.head()

from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import metrics

#split dataset
X_train, X_test, y_train, y_test = train_test_split(dataX, dataY, test_size=0.33)


regr = linear_model.LinearRegression()
#train model
regr.fit(X_train,y_train)
#predict with test 
y_=regr.predict(X_test)
#get the cross validation score 
acc = cross_val_score(regr, dataX, dataY)

print('Coefficients:', regr.coef_)
print('Variance score: %.2f' % regr.score(X_train,y_train)) 
print('Mean Cross Validation Score: %.2f' % np.mean(acc))
print('Mean Squared Error: %.2f' % np.sqrt(metrics.mean_squared_error(y_test,y_)))